# Use a minimal base Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy app files
COPY . .
COPY deps /deps

# Install dependencies using local cache only
RUN pip install --no-index --find-links=/deps --no-cache-dir -r requirements.txt

# Default command
CMD ["python", "analyzer.py"]
